parameters:
    cloud.strictly.default.categories: false

services:
    elasticsearch.manager:
        class: BackBeeCloud\Elasticsearch\ElasticsearchManager
        arguments: [ "@bbapp" ]

    content.category_listener:
        class: BackBeePlanet\Standalone\ContentCategoryListener
        arguments:
            - "%cloud.default.ordered.categories%"
            - "%cloud.override.default.categories%"
            - "%cloud.strictly.default.categories%"
            - "@routing"
